server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
<<<<<<< HEAD

  server:
    enable-self-preservation: false


=======
  server:
    enable-self-preservation: false
    server:
      enable-self-preservation: false
>>>>>>> 751cb76366088621dc4c64ee9dda2eb48481e68c
