server:
  port: 8080


spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: web
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

